// apps/allystudio/components/ui/button.tsx
import * as React from "react"
import { Slot } from "@radix-ui/react-slot"
import { cn } from "@workspace/ui/lib/utils"
import { cva, type VariantProps } from "class-variance-authority"

const buttonVariants = cva(
  "inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0",
  {
    variants: {
      variant: {
        default: "bg-primary text-primary-foreground hover:bg-primary/90",
        destructive:
          "bg-destructive text-destructive-foreground hover:bg-destructive/90",
        outline:
          "border border-input bg-background hover:bg-accent hover:text-accent-foreground",
        secondary:
          "bg-secondary text-secondary-foreground hover:bg-secondary/80",
        ghost: "hover:bg-accent hover:text-accent-foreground",
        link: "text-primary underline-offset-4 hover:underline",
      },
      size: {
        default: "h-10 px-4 py-2",
        sm: "h-9 rounded-md px-3",
        lg: "h-11 rounded-md px-8",
        icon: "h-10 w-10",
      },
    },
    defaultVariants: {
      variant: "default",
      size: "default",
    },
  }
)

export interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement>,
    VariantProps<typeof buttonVariants> {
  asChild?: boolean
}

const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className, variant, size, asChild = false, ...props }, ref) => {
    const Comp = asChild ? Slot : "button"
    return (
      <Comp
        className={cn(buttonVariants({ variant, size, className }))}
        ref={ref}
        {...props}
      />
    )
  }
)
Button.displayName = "Button"

export { Button, buttonVariants }

// apps/allsight/app/components/Button.vue
<script lang="ts">
import { computed, defineComponent, h, useAttrs, useSlots } from "vue"

export default defineComponent({
  props: {
    color: {
      type: String as () => "gray" | "black",
      default: "black",
    },
    asChild: {
      type: Boolean,
      default: false,
    },
  },
  setup(props) {
    const slots = useSlots()
    const attrs = useAttrs()

    const buttonClasses = computed(() => {
      const baseClasses =
        "inline-flex items-center justify-center gap-2 whitespace-nowrap text-sm font-medium ring-white ring-black transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0 h-8 px-4 py-2"

      const colorClasses = {
        gray: "bg-gray-500 text-white hover:bg-gray-600",
        black: "bg-black text-white hover:bg-gray-800",
      }

      return `${baseClasses} ${colorClasses[props.color!]}`
    })

    return () => {
      if (!props.asChild) {
        const { class: classAttr, ...otherAttrs } = attrs
        const mergedClass = classAttr
          ? `${buttonClasses.value} ${classAttr}`
          : buttonClasses.value

        return h(
          "button",
          {
            class: mergedClass,
            ...otherAttrs,
          },
          slots.default?.()
        )
      }

      const slotContent = slots.default?.()
      if (!slotContent || slotContent.length === 0) {
        return h("button", {
          class: buttonClasses.value,
          ...attrs,
        })
      }

      const childVNode = slotContent[0]
      if (!childVNode) {
        return
      }

      const existingClass = childVNode.props?.class || ""
      const mergedClass = `${existingClass} ${buttonClasses.value}`.trim()

      // @ts-ignore - Dynamic component type from slot content
      return h(
        childVNode.type,
        {
          ...childVNode.props,
          ...attrs,
          class: mergedClass,
        },
        childVNode.children
      )
    }
  },
})
</script>
